global:
  supported_tools:  [
    "iStar", "xfuse", "ImSpiRE", "TESLA"
  ]
  supported_output_formats: [
    "raw", "h5ad"
  ]
  iStar:
    conda_env_prefix: "iStar"
    temp_dir: "/home/yiriso/Research/Super-resolvedST/SuperResolvedST-Pipeline/iStar/temp"
    tool_script: "/home/yiriso/Research/Super-resolvedST/SuperResolvedST-Pipeline/iStar/Run-iStar.sh"
    model_params:
      iStar_home: "/home/yiriso/Research/Super-resolvedST/istar/istar-master/"
      epochs: 400
      device: "cuda"
      GPU_id: 0
      num_jobs: 2
      num_states: 5
  xfuse:
    conda_env_prefix: "xfuse-cuda11.7"
    temp_dir: "/home/yiriso/Research/Super-resolvedST/SuperResolvedST-Pipeline/xfuse/temp"
    tool_script: "/home/yiriso/Research/Super-resolvedST/SuperResolvedST-Pipeline/xfuse/Run-xfuse.sh"
    model_params:
      GPU_id: 0
      batch_size: 3
      epochs: 100000
      learning_rate: 0.0003
  ImSpiRE:
    conda_env_prefix: "imspire"
    temp_dir: "/home/yiriso/Research/Super-resolvedST/SuperResolvedST-Pipeline/ImSpiRE/temp"
    tool_script: "python /home/yiriso/Research/Super-resolvedST/SuperResolvedST-Pipeline/ImSpiRE/Run-ImSpiRE.py"
    model_params:
      Mode: 1
      FeatureParam_ProcessNumber: 12
      OptimalTransportParam_NumNeighbors: 5
      OptimalTransportParam_Epsilon: 0.001
      OptimalTransportParam_NumIterMax: 50
  TESLA:
    conda_env_prefix: "DataReader"
    temp_dir: "/home/yiriso/Research/Super-resolvedST/SuperResolvedST-Pipeline/TESLA/temp"
    tool_script: "python /home/yiriso/Research/Super-resolvedST/SuperResolvedST-Pipeline/TESLA/Run-TESLA.py"
    model_params:
      num_nbs: 3
      color_scale: 1
      dist_decay_exp : 2
default:
  visium_serial:  1
  format: "h5ad"
  super_pixel_size: 16
  model: "iStar"
  preprocess:
    n_top_hvg: 2000     # -1 will take all of gene
    min_counts: 10
    auto_mask: True
    mask_image_path: False
    require_genes: False
  postprocess:
    normalize: False