global:
  supported_tools:  [
    "iStar", "xfuse", "ImSpiRE", "TESLA"
  ]
  conda_env_prefix:
    iStar:  "iStar"
    xfuse:  "xfuse-cuda11.7"
    ImSpiRE:  "imspire"
    TESLA:  "DataReader"
  temp_dir:
    iStar:  "./iStar/temp"
    xfuse:  "./xfuse/temp"
    ImSpiRE:  "./ImSpiRE/temp"
    TESLA:  "./TESLA/temp"
  tool_scripts:
    iStar:  "./iStar/Run-iStar.sh"
    xfuse:  "./xfuse/Run-xfuse.sh"
    # ImSpiRE:  "./ImSpiRE/Run-ImSpiRE.sh"
    ImSpiRE:  "python ./ImSpiRE/Run-ImSpiRE.py --prefix"
    TESLA:  "python ./TESLA/Run-TESLA.py --prefix"
default:
  visium_serial:  1
  format: "h5ad"
  super_pixel_size: 16
  model: "iStar"
  preprocess:
    n_top_hvg: 2000
    min_counts: 10
    auto_mask: True
    mask_image: False
    require_genes: False
  postprocess:
    normalize: False