[xfuse]
network_depth = 6
network_width = 16
device =
gene_regex = ".*"
min_counts = 0

[expansion_strategy]
type = "DropAndSplit"
[expansion_strategy.DropAndSplit]
max_metagenes = 50

[optimization]
batch_size =
epochs =
learning_rate =
patch_size =

[analyses]
[analyses.metagenes]
type = "metagenes"
[analyses.metagenes.options]
method = "pca"

[analyses.gene_maps]
type = "gene_maps"
[analyses.gene_maps.options]
gene_regex = ".*"
writer = "tensor"

[slides]
[slides.section1]
data = "section1/data.h5"
[slides.section1.covariates]
section = 1


